import collections
import glob
import operator
import re

impact = collections.defaultdict(float)
# Requires the files generated by running main.py with a perfectly
# matching budget so that the MonoTuner evaluates all flags once
for file in glob.glob("results/tuning_24*MonoTuner.txt"):
    with open(file) as fh:
        r = re.compile(r"([^ ]+) (\d*\.\d+)")
        for line in fh:
            m = r.match(line)
            assert m
            flags = m.group(1)
            speedup = float(m.group(2))
            if speedup > 1.01:
                impact[flags] += speedup
impact = sorted(impact.items(), key=operator.itemgetter(1), reverse=True)
with open("gcc_flags/flags_impact.txt", "w") as fh:
    fh.write(("# Flags sorted in descending order by their individual impact"
              " over the cBenchmarks\n"))
    for flag, speedup in impact:
        flag = flag.replace("-fno-", "-f", 1)
        fh.write(f"{flag}\n")
